"""add picture table

Revision ID: a4b6b89ae0d9
Revises: 1b6ae3e8c5f7
Create Date: 2024-06-04 12:40:21.019417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b6b89ae0d9'
down_revision: Union[str, None] = '1b6ae3e8c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
